import { Providers } from "./providers";
import { Inter } from "next/font/google";
import Header from "@/components/header/Header.jsx";
import Footer from "../components/footer/Footer.jsx";

import "./globals.css"

const font = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  return (
    <html lang="uk">
      <body className={font.className}>
        <Providers>
            <Header />
            <main>{children}</main>
            <Footer />
        </Providers>
      </body>
    </html>
  );
}
